spellername = "German"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "German spellchecker"
de = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for German, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
de = "TRANSLATE: A spellchecker for German, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.de"

[windows]
system_product_code = "{5C30B55C-E152-4880-8D0E-0D906A933952}_is1"
legacy_product_codes = [
    { value = "B8037872-FCFA-4C20-8D4F-B1627BD100C9", kind = "nsis" },
    { value = "58029E28-E423-4AED-8691-61F1E1701B81", kind = "nsis" }
]
