template = "https://github.com/giellalt/template-lang-und"
rev_id = 346
template_sha = "f98c2a37b9866895a157f22bea282f596e7a321a"

[replacements]
__GLOTTOLOG_ID__ = "stan1295"
__REPO__ = "lang-deu"
__UND2C__ = "de"
__UNDEFINED__ = "German"
__UND__ = "deu"
