template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "stan1295"
__REPO__ = "lang-deu"
__UND2C__ = "de"
__UNDEFINED__ = "German"
__UND__ = "deu"
