template = "https://github.com/giellalt/template-lang-und"
rev_id = 283
template_sha = "bfef967c632b9041975725ec13da8c2dfe66b74e"

[replacements]
__GLOTTOLOG_ID__ = "stan1295"
__REPO__ = "lang-deu"
__UND2C__ = "de"
__UNDEFINED__ = "German"
__UND__ = "deu"
