[package]
name = "deu"
human_name = "German"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.deu]
filename = "de-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-deu"
platform = "windows"
uuid = "B8037872-FCFA-4C20-8D4F-B1627BD100C9"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.de"
package = "speller-deu"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-deu-mso"
platform = "windows"
uuid = "58029E28-E423-4AED-8691-61F1E1701B81"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-deu"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
